version: '3.7'

services:
  react-app:
    build: .
    container_name: react-portfolio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react-portfolio.rule=Host(`portfolio.hector-bidan.fr`)"
      - "traefik.http.routers.react-portfolio.entrypoints=web"
      - "traefik.http.routers.react-portfolio-secured.rule=Host(`portfolio.hector-bidan.fr`)"
      - "traefik.http.routers.react-portfolio-secured.entrypoints=websecure"
      - "traefik.http.routers.react-portfolio-secured.tls.certresolver=myresolver"