api:
  insecure: true

log:
  level: DEBUG

providers:
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: ":85"

  websecure:
    address: ":8445"

certificatesResolvers:
  myresolver:
    acme:
      email: hector-bidan@gmail.com
      storage: /letsencrypt/acme.json
      tlsChallenge: {}
